### ISSUE TITLE
Repository structure is not convenient

### ISSUE THREAD

**Issue by volodymyrrudyi** [lwaddicor/spring-startup-analysis#2]
Currently, the actual pom.xml is located inside the "analyzer" subfolder. Usually users expect to see the **pom.xml** in the root of the project so the flow is like this:

```bash
git clone <repo-url> <dir-name>
cd <dir-name>
mvn clean install
```

**Comment by lwaddicor** [comment]
I will create a top level pom to allow the whole project to compile from the top level

**Comment by lwaddicor** [comment]
Done
