### ISSUE TITLE
No need to keep *.backup files in the repo

### ISSUE THREAD

**Issue by volodymyrrudyi** [lwaddicor/spring-startup-analysis#3]
There is a **pom.xml.versionsBackup** which doesn't make sense since the VCS is used. Also it confuses the IntelliJ Idea on the project import:

![image](https://cloud.githubusercontent.com/assets/875828/23202474/bd45cf10-f8e6-11e6-9cc5-1ec81dccef41.png)

**Comment by lwaddicor** [comment]
I have removed the other pom.versionsBackup file, and added to gitignore.

Hopefully this shouldn't happen again.

Thanks
